<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__payGradename</name>
   <tag></tag>
   <elementGuidId>25097693-276e-4916-9081-70dc8aa7b628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payGrade_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payGrade_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01cc7cc8-3658-4dc6-8fff-e1a711862854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c4d22ae-3dc5-42ea-8010-f7d7516e9084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payGrade[name]</value>
      <webElementGuid>1578d99c-d58e-479d-8aec-53e4b36fea20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payGrade_name</value>
      <webElementGuid>688a1d96-1610-49da-af35-0b926451cdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payGrade_name&quot;)</value>
      <webElementGuid>bbf7e969-8b24-4a86-bbb3-912f4eb9a516</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payGrade_name']</value>
      <webElementGuid>7fba3219-4a85-44d9-9ffe-ee9e7177cda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmPayGrade']/fieldset/ol/li/input</value>
      <webElementGuid>b98b2fff-f461-4ab3-b29b-5e7d19551975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>479a0b1d-2da5-46ce-9057-ed825ea7b92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'payGrade[name]' and @id = 'payGrade_name']</value>
      <webElementGuid>a781fb39-e522-428c-846c-90d3363186fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
