<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comment_Comment</name>
   <tag></tag>
   <elementGuidId>c84899b8-b104-4d7d-8881-939e0aa97bbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtComment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtComment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e3dd7fcf-1f84-4cfa-8671-622a558bb06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Comment</value>
      <webElementGuid>e7c2c065-2c42-41a9-9ff7-ff8dc66b6bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtComment</value>
      <webElementGuid>8316cfeb-a719-4ce2-a732-bbf6ea1536d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtComment&quot;)</value>
      <webElementGuid>bcd257cc-80c6-4f36-a43c-155646b02802</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtComment']</value>
      <webElementGuid>994b50b2-bec6-420a-a3b0-900f0c212485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='timesheetActionFrm']/fieldset/ol/li/textarea</value>
      <webElementGuid>f90579b1-5462-450c-8b28-86dfc2a4a6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b19073d5-160c-492c-bd9a-b0ce74554477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'Comment' and @id = 'txtComment']</value>
      <webElementGuid>d2a906c8-d8eb-441c-8386-9d2b43fe4628</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
